<?php Security::injectAntiCSRFHeader();?>
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />

    <title><?= _(PROJECT_NAME); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <?= Tag::css('bulma.min'); ?>
    
</head>

<body>
	
	<?php echo $yield; ?>
    
</body>

</html>
	

